[book]
title = "TOPAZ LEAF"
authors = ["Burgess Leo"]
description = "The program book about Linux."
language = "zh-cn"
src = "src"


[output.html]
default-theme = "rust"
preferred-dark-theme = "rust"
git-repository-url = "https://github.com/lxp731/topazleaves.git"
mathjax-support = true

[output.html.fold]
enable = false
level = 0

[preprocessor.plantuml]
plantuml-cmd="/usr/bin/plantuml"